DROP TABLE IF EXISTS API_CALLS_LOG;
 
CREATE TABLE API_CALLS_LOG (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  method_name VARCHAR(250) NOT NULL,
  response_time BIGINT NOT NULL,
  creation_date TIMESTAMP NOT NULL
);
